##
# Default settings for all notifiers.
#
default_settings:
  retries: 3
  async: true  
  on_error: ignore
  on_error_notifiers:
    - id: slack
      params:
        callback_url: https://httpbin.org/post

notifiers:
  - id: test
    desc: Test1
    params:
      api_key: hello-world-api-key
      app_id: app-id-1

  - id: test
    desc: Test2
    params:
      api_key: hello-world-api-key-2
      app_id: app-id-1
