##
# Default settings for all notifiers.
#
default_settings:
  retries: 3
  # Do you prefer uampnotif to call all notifiers concurrently?
  async: true
  # What do you want us to do in case of a failure to notify one of the
  # downstream systems?
  #
  #   Accepted values:
  #    - ignore: Do nothing
  #    - fatal: Exit with 1 if on_error_notifiers is set, notify before exiting.
  #    - no_error_notifiers: Mute notifying the on_error_notifiers
  #
  on_error: ignore
  # TODO: Future feature
  # Do you prefer to notify a list of notifiers if error arises?
  on_error_notifiers:
    - id: slack
      params:
        callback_url: https://httpbin.org/post

##
# A list of notifiers to be invoked whenever uampnotif is launched.
#
notifiers:
  ##
  # id: Must match with corresponding integration id:
  #
  - id: newrelic
    ##
    # You can use go-template with .Env for all param value.
    #
    params:
      callback_url: https://httpbin.org/post
      api_key: '{{.FindEnv "NEWRELIC_API_KEY"}}'

  - id: rollbar
    params:
      access_token: hello-access-token
      environment: staging
      rollbar_username: hello-rollbar-user
      comment: Exception from Rollbar

  - id: slack
    params:
      callback_url: https://httpbin.org/post

  - id: sox-auditor
    params:
      repo_name: test/repo
      secret: hello-world-secret
    ##
    # Override global settings. You can only add the one you may prefer.
    # Uampnotif merges the settings below with the globally exposed settings.
    #
    settings:
      on_error: fatal
